apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-delivery
  labels:
    app: food-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-delivery
  template:
    metadata:
      labels:
        app: food-delivery
    spec:
      containers:
      - name: food-delivery
        image: food-delivery
        imagePullPolicy: Never
        ports:
        - containerPort: 80
